id: A411998AD
title: Aspiration for the Country’s Welfare
type: translation
pechas:
- ICF9F14F1
- IB4799927
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:16.398687
  last_modified_at: 2023-01-04 11:51:16.398696
  collections:
  - Fifteenth Karmapa Series
  - Works of Tibetan Masters
alignment_to_base:
  ICF9F14F1/4F5F: 7F53
  IB4799927/2285: 7F53
